version: '3.7'

services:   
  gostprojectapi:
    image: ${DOCKER_REGISTRY-}gostprojectapi
    ports:
      - 7277:443
      - 5244:80
    build:
      context: .
      dockerfile: GostProjectApi/Dockerfile
    depends_on:
      mysql123:
        condition: service_healthy
    networks:
      - my-network

  mysql123:
    image: mcr.microsoft.com/mysql/server
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '' -Q 'SELECT 1'" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 10s
    restart: always
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=
    networks:
      - my-network
  gostprojectclient:
    image: gostprojectclient
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

      
networks:
  my-network: {}