version: '3.4'

services:
  gostprojectclient:
    image: gostprojectclient
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
