// <auto-generated />
using System;
using GostProjectAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GostProjectAPI.Migrations
{
    [DbContext(typeof(GostDBContext))]
    [Migration("20231225123802_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GostProjectAPI.Data.Entities.Company", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasColumnType("VARCHAR(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.HasKey("ID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("GostProjectAPI.Data.Entities.Gost", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("AcceptanceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("AcceptanceLevel")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("ActionStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Amendments")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<string>("Denomination")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<uint>("GostIdReplaced")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("IntrodutionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormativeReferences")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OKPDCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<string>("OKSCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<ulong>("RequestsNumber")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.HasKey("ID");

                    b.HasIndex("GostIdReplaced");

                    b.ToTable("Gosts");
                });

            modelBuilder.Entity("GostProjectAPI.Data.Entities.Keyphrase", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("GostId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.HasKey("ID");

                    b.HasIndex("GostId");

                    b.ToTable("Keyphrases");
                });

            modelBuilder.Entity("GostProjectAPI.Data.Entities.Keyword", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("GostId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.HasKey("ID");

                    b.HasIndex("GostId");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("GostProjectAPI.Data.Entities.User", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("WorkCompanyID")
                        .HasColumnType("int unsigned");

                    b.HasKey("ID");

                    b.HasIndex("WorkCompanyID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GostProjectAPI.Data.Entities.Gost", b =>
                {
                    b.HasOne("GostProjectAPI.Data.Entities.Gost", "GostReplaced")
                        .WithMany()
                        .HasForeignKey("GostIdReplaced")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GostReplaced");
                });

            modelBuilder.Entity("GostProjectAPI.Data.Entities.Keyphrase", b =>
                {
                    b.HasOne("GostProjectAPI.Data.Entities.Gost", "Gost")
                        .WithMany("Keyphrases")
                        .HasForeignKey("GostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gost");
                });

            modelBuilder.Entity("GostProjectAPI.Data.Entities.Keyword", b =>
                {
                    b.HasOne("GostProjectAPI.Data.Entities.Gost", "Gost")
                        .WithMany("Keywords")
                        .HasForeignKey("GostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gost");
                });

            modelBuilder.Entity("GostProjectAPI.Data.Entities.User", b =>
                {
                    b.HasOne("GostProjectAPI.Data.Entities.Company", "WorkCompany")
                        .WithMany()
                        .HasForeignKey("WorkCompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkCompany");
                });

            modelBuilder.Entity("GostProjectAPI.Data.Entities.Gost", b =>
                {
                    b.Navigation("Keyphrases");

                    b.Navigation("Keywords");
                });
#pragma warning restore 612, 618
        }
    }
}
