export const searchDict = {
  designation: "Обозначение",
  denomination: "Название",
  oksCode: "Код ОКС",
  okpdCode: "Код ОКПД",
  text: "Текст стандарта",
  acceptanceYear: "Год принятия",
  introdutionYear: "Год введения",
  content: "Содержание",
  keywords: "Ключевые слова",
  keyphrases: "Ключевые фразы",
  acceptanceLevel: "Уровень принятия",
  actionStatus: "Статус",
  gostIdReplaced: "Принят взамен",
  developerName: "Разработчик",
};
